#!/usr/bin/env python
# -*- coding:utf-8 -*-

import socket

def get_gateway_heart():
    SENDERIP = "0.0.0.0"
    MYPORT = 9898
    MYGROUP = '224.0.0.50'

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
    #allow multiple sockets to use the same PORT number
    sock.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
    #Bind to the port that we know will receive multicast data
    sock.bind((SENDERIP,MYPORT))
    #tell the kernel that we are a multicast socket
    #sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 255)
    #Tell the kernel that we want to add ourselves to a multicast group
    #The address for the multicast group is the third param
    status = sock.setsockopt(socket.IPPROTO_IP,
        socket.IP_ADD_MEMBERSHIP,
        socket.inet_aton(MYGROUP) + socket.inet_aton(SENDERIP));

    #sock.setblocking(0)
    #ts = time.time()
    data, addr = sock.recvfrom(1024)
    data_str=str(data,encoding='utf-8')
#    sock.close()
    return data_str


if __name__=='__main__':
    while True:
        tmp=get_gateway_heart()
        print(tmp)
